### ISSUE TITLE
Feature Request - support for config based (Serilog.Settings.Configuration)

### ISSUE THREAD

**Issue by srinivasanvee** [JohnLTaylor/Serilog.Enrichers.TraceIdentifier#1]
I understand it works when i configure it directly with startup.cs, but not with Serilog.Settings.Configuration (as there is no direct way to pass the dependency IHttpContextAccessor), that would be really helpful feature

Please let me know if it already supported by chance

**Comment by JohnLTaylor** [comment]
"Serilog": {
    "MinimumLevel": {
      "Default": "Verbose",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "LiterateConsole",
        "Args": {
          "outputTemplate": "[{Timestamp:HH:mm:ss.fff%K} | {MachineName} | {TraceIdentifier} | {SourceContext:l} | {Level:u3}]{NewLine}{Message:lj}{NewLine}{Exception}"
        }
      },
      {
        "Name": "Debug",
        "Args": {
          "outputTemplate": "[{Timestamp:HH:mm:ss.fff%K} | {MachineName} | {TraceIdentifier} | {SourceContext:l} | {Level:u3}]{NewLine}{Message:lj}{NewLine}{Exception}"
        }
      },
      {
        "Name": "Trace",
        "Args": {
          "outputTemplate": "[{Timestamp:HH:mm:ss.fff%K} | {MachineName} | {TraceIdentifier} | {SourceContext:l} | {Level:u3}]{NewLine}{Message:lj}{NewLine}{Exception}"
        }
      }
    ],
    "Enrich": [
      "FromLogContext",
      "WithMachineName",
      "WithTraceIdentifier"
    ]
  },

**Comment by srinivasanvee** [comment]
It works, thank you for the reply
